name: 'fetchGodot'
description: 'Load godot engine and export templates and prepares docker image'
inputs:
  godot-version: 
    description: 'Godot Version to use'
    required: true
    default: '3.4'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      with:
        GODOT_VERSION: ${{ inputs.godot-version }}
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.godot-version }}