name: Conversion & build job(s)
on: push
#on: 
#  push:
#    branches:
#      - main

jobs:
  build:
    name: Coverting & setting live
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: main
        token: ${{ secrets.MY_TOKEN || github.token }}

    - name: Fetch godot version
      id: fetchGodot
      uses: ./main/.github/actions/fetchGodot
      with:
        godot-version: 3.4

    - name: Build release
      id: 
      uses: ./main/.github/actions/exportGodotProject
      with:
        export-pack: false
        export-debug: false
        export-platform: "Linux/X11"
        project-directory: "./example-project"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./export-pck
          ./export-debug
          ./export-platform
    