name: 'fetchGodot'
description: 'Load godot engine and export templates'
inputs:
  godot-version: 
    description: 'Godot Version to use'
    required: true
    default: '3.4'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.godot-version }}